## Bin
bin: "bin"

clinical_file: "data_all/clinical_curated/NIHMS978596-supplement-1.xlsx"
ppi_file: "panda_input_primary/ppi_tcga_primary.tsv"
motif_file: "panda_input_primary/motif_tcga_primary.tsv"
expression_file: "panda_input_primary/exp_tcga_primary.tsv"
samples_file: "panda_input_primary/samples_cancers_primary.tsv"

cancer_color_file: "data_all/samples/cancer_colors.txt"
immune_file: "data_all/cibersortx/CIBERSORTx_Results.txt"
cancer_types: ["ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC", "ESCA", "GBM",
              "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO",
              "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA",
              "THYM", "UCEC", "UCS", "UVM"]
threshold_cox: [20, 50]
output_dir: "data_individual_cancers"
fig_dir: "figs"
alpha: 0.3
number_cores: 50
number_folds: 5
number_times: 100
gene_id: "CD274"