## Bin
bin: "workflow/bin"

## clinical data
clinical_file: "resources/clinical_curated/NIHMS978596-supplement-1.xlsx"
clinical_file_rdata: "resources/clinical_curated/clin.RData"
## pathways
gmt_file: "resources/MSigDb/c2.cp.reactome.v7.1.symbols.gmt"
pathways_hierarchy_file: "resources/MSigDb/pathways_hierarchy.txt"
pathways_hsa_id_file: "resources/MSigDb/reactome_pathways_hsa_id.txt"
list_of_pathways_file: "resources/MSigDb/list_of_pathways.txt"
## samples
batch_file: "resources/samples/batch_information.txt"
cancer_color_file: "resources/samples/cancer_colors.txt"
# priors


ppi_file: "panda_input_primary/ppi_tcga_primary.tsv"
motif_file: "panda_input_primary/motif_tcga_primary.tsv"
expression_file: "panda_input_primary/exp_tcga_primary.tsv"
samples_file: "panda_input_primary/samples_cancers_primary.tsv"


immune_file: "data_all/cibersortx/CIBERSORTx_Results.txt"


cancer_types: ["ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC", "ESCA", "GBM",
              "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO",
              "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA",
              "THYM", "UCEC", "UCS", "UVM"]


number_cores_mbatch: 4
download_files: "NO" # Set to "YES" to download the expression files (takes very long time)
datatypes: ["expression", "indegree"]
threshold_cox: [20, 50]
output_dir: "results"
output_dir_individual_cancers: "data_individual_cancers"
output_dir_all_cancers: "data_all"

fig_dir: "figs"
alpha: 0.3
number_cores: 20
number_folds: 5
number_times: 100
gene_id: "CD274"
# for cola clustering #
number_cores_cola: 30
top_value_method: "ATC"
partition_method: "kmeans"
max_k: 6
