## Bin
bin: "workflow/bin"

## Directories
resources_dir: "resources"
results_dir: "results"
workflow_dir: "workflow"
envs: "workflow/envs"

## Analysis Type Configuration
## - "full_workflow": Complete pipeline execution (takes several weeks)
## - "precomputed": Downloads intermediate files from Zenodo 
##   Allows rapid reproduction of main manuscript figures without
##   lengthy network calculations
analysis_type: "precomputed"  # Change to "full_workflow" for entire analysis (will take weeks)

## Zenodo
zenodo_record_id: "17235372"  
zenodo_resource_filename: "resources.zip"  
zenodo_batch_analysis_filename: "batch_analysis.zip"  
zenodo_individual_cancers_filename: "data_individual_cancers.zip"  
zenodo_gdc_filename: "combined_gdc_data.zip"
## Files that should be available in resources_dir
## clinical data
clinical_file: "resources/clinical_curated/NIHMS978596-supplement-1.xlsx"
clinical_file_rdata: "resources/clinical_curated/clin.RData"
## pathways
gmt_file: "resources/MSigDb/c2.cp.reactome.v7.1.symbols.gmt"
pathways_hierarchy_file: "resources/MSigDb/pathways_hierarchy.txt"
pathways_hsa_id_file: "resources/MSigDb/reactome_pathways_hsa_id.txt"
list_of_pathways_file: "resources/MSigDb/list_of_pathways.txt"
## samples
batch_file: "resources/samples/batch_information.txt"
cancer_color_file: "resources/samples/cancer_colors.txt"
# priors
ppi_file: "resources/priors/ppi_prior.tsv"
motif_file: "resources/priors/tf_prior_names_fixed.tsv"
samples_file: "resources/samples/samples_cancers_clean.tsv"

immune_file: "resources/cibersortx/CIBERSORTx_Results.txt"
cancer_types: ["ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC", "ESCA", "GBM",
              "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO",
              "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA",
              "THYM", "UCEC", "UCS", "UVM"]
batches: ["platform", "CancerType", "Purity_singscore", "Center", "TSS",
         "Plates", "Day", "Month", "Year"]
number_cores_mbatch: 4
datatypes: ["expression", "indegree"]
threshold_cox: [20, 50]
output_dir: "results"
output_dir_individual_cancers: "results/data_individual_cancers"
output_dir_all_cancers: "results/data_all"

fig_dir: "results/figs"
ncores_porcupine: 30
alpha: 0.3
number_cores: 20
number_folds: 5
number_times: 100
gene_id: "CD274"
# for cola clustering #
number_cores_cola: 30
top_value_method: "ATC"
partition_method: "kmeans"
max_k: 6
